### ISSUE TITLE
jinja2.exceptions.UndefinedError

### ISSUE THREAD

**Issue by anjelo42** [cober2019/IOS-XE-Ops#1]
Hi,
Raising above issue when for first time try to adding a device.

jinja2.exceptions.UndefinedError

jinja2.exceptions.UndefinedError: 'str object' has no attribute 'items'
Traceback (most recent call last)

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2464, in __call__

    return self.wsgi_app(environ, start_response)

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2450, in wsgi_app

    response = self.handle_exception(e)

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1867, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise

    raise value

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app

    response = self.full_dispatch_request()

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise

    raise value

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request

    rv = self.dispatch_request()

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "/RoutingGUI/app/base/routes.py", line 126, in get_routing

    return render_template('routing.html', interfaces=get_interfaces[0],

    File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 137, in render_template

    return _render(

    File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 120, in _render

    rv = template.render(context)

    File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1090, in render

    self.environment.handle_exception()

    File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 832, in handle_exception

    reraise(*rewrite_traceback_stack(source=source))

    File "/usr/local/lib/python3.8/dist-packages/jinja2/_compat.py", line 28, in reraise

    raise value.with_traceback(tb)

    File "/RoutingGUI/app/home/templates/routing.html", line 1, in top-level template code

    {% extends 'layouts/base.html' %}

    File "/RoutingGUI/app/base/templates/layouts/base.html", line 48, in top-level template code

    {% block content %}{% endblock content %}

    File "/RoutingGUI/app/home/templates/routing.html", line 218, in block "content"

    {% for k, v in ospf.items() %}

    jinja2.exceptions.UndefinedError: 'str object' has no attribute 'items'

**Comment by cober2019** [comment]
Thank for contributing to the project. I've update the code, please verify that it is working correctly now. If downloaded from docker then I would need some time to update.

**Comment by cober2019** [comment]
Issue resolved

**Comment by cober2019** [comment]
Issue resolved
